name: Test package

on: [push, pull_request]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        shell: bash -el {0}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: ["3.10", "3.11", "3.12"]
    steps:
    - uses: actions/checkout@v5
    - name: Set up Python ${{ matrix.python-version }}
      uses: conda-incubator/setup-miniconda@v3
      with:
        auto-update-conda: true
        python-version: ${{ matrix.python-version }}
        activate-environment: numpy-financial-dev
        environment-file: environment.yml
        auto-activate-base: false
    - name: Conda metadata
      run: |
        conda info
        conda list
    - name: Lint
      run: |
        set -euo pipefail
        # Tell us what version we are using
        ruff version
        # Check the source file, ignore type annotations (ANN) for now.
        ruff check numpy_financial/ benchmarks/ --ignore F403 --select E,F,B,I
    - name: Build project
      run: |
        spin build -v --clean
    - name: Test with pytest
      run: |
        spin test -- --doctest-modules
